// Build-time generator: scans the skills directory, validates it with the same
// rules the CLI applies at runtime, and emits a Zig source file embedding every
// skill file verbatim.
const std = @import("std");
const specrail = @import("specrail");

fn writeZigString(writer: *std.Io.Writer, bytes: []const u8) std.Io.Writer.Error!void {
    try writer.writeByte('"');
    for (bytes) |byte| {
        switch (byte) {
            '"' => try writer.writeAll("\\\""),
            '\\' => try writer.writeAll("\\\\"),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            else => {
                if (byte < 0x20 or byte == 0x7f) {
                    var buffer: [8]u8 = undefined;
                    try writer.writeAll(std.fmt.bufPrint(&buffer, "\\x{x:0>2}", .{byte}) catch unreachable);
                } else {
                    try writer.writeByte(byte);
                }
            },
        }
    }
    try writer.writeByte('"');
}

fn generate(writer: *std.Io.Writer, skills: []const specrail.adapters.Skill) std.Io.Writer.Error!void {
    try writer.writeAll(
        \\// Generated by tools/embed_skills.zig from the skills/ directory.
        \\// Do not edit; run `zig build` to regenerate.
        \\
        \\pub const SkillFile = struct {
        \\    path: []const u8,
        \\    content: []const u8,
        \\};
        \\
        \\pub const Skill = struct {
        \\    id: []const u8,
        \\    name: []const u8,
        \\    description: []const u8,
        \\    files: []const SkillFile,
        \\};
        \\
        \\pub const skills = [_]Skill{
        \\
    );
    for (skills) |skill| {
        try writer.writeAll("    .{\n        .id = ");
        try writeZigString(writer, skill.id);
        try writer.writeAll(",\n        .name = ");
        try writeZigString(writer, skill.name);
        try writer.writeAll(",\n        .description = ");
        try writeZigString(writer, skill.description);
        try writer.writeAll(",\n        .files = &.{\n");
        for (skill.files) |file| {
            try writer.writeAll("            .{ .path = ");
            try writeZigString(writer, file.path);
            try writer.writeAll(", .content = ");
            try writeZigString(writer, file.content);
            try writer.writeAll(" },\n");
        }
        try writer.writeAll("        },\n    },\n");
    }
    try writer.writeAll("};\n");
}

pub fn main(init: std.process.Init) u8 {
    const arena = init.arena.allocator();
    var args = std.process.Args.Iterator.initAllocator(init.minimal.args, init.gpa) catch {
        std.debug.print("embed-skills: unable to read arguments\n", .{});
        return 1;
    };
    defer args.deinit();
    _ = args.next();
    const skills_dir = args.next() orelse {
        std.debug.print("embed-skills: usage: embed-skills <skills-dir> <output-file>\n", .{});
        return 1;
    };
    const out_path = args.next() orelse {
        std.debug.print("embed-skills: usage: embed-skills <skills-dir> <output-file>\n", .{});
        return 1;
    };

    const skills = specrail.generate.readSkillsFromDir(arena, init.io, skills_dir) catch {
        std.debug.print("embed-skills: {s}\n", .{specrail.errors.message});
        return 1;
    };

    var out: std.Io.Writer.Allocating = .init(arena);
    generate(&out.writer, skills) catch {
        std.debug.print("embed-skills: out of memory\n", .{});
        return 1;
    };

    var file = std.Io.Dir.cwd().createFile(init.io, out_path, .{ .truncate = true }) catch {
        std.debug.print("embed-skills: unable to write {s}\n", .{out_path});
        return 1;
    };
    defer file.close(init.io);
    file.writeStreamingAll(init.io, out.written()) catch {
        std.debug.print("embed-skills: unable to write {s}\n", .{out_path});
        return 1;
    };
    return 0;
}
